Implement uncompress functionality for PDF files
py-pdf/pdfly pull request #66
Opened 2024-10-30 16:02 UTC by Kaos599

- Added a new `uncompress.py` script to decompress Flate-encoded content streams in PDF files.
- Updated `main` function to handle PDF input and output paths.
- Modified `pyproject.toml` to include the I001 rule for Ruff linter to ignore specific linting issues, since it was conflicting with black.

2024-11-04 13:22 UTC, Lucas-C commented on pdfly/uncompress.py
> +            print(f"Decompression error: {e}")
```suggestion
        except zlib.error as error:
            print(f"Some content stream with /FlateDecode failed to be decompressed: {error}")
```
Your strategy there is that a `zlib.error` should NOT interrupt the command?

I'm OK with that, but maybe the error message should be slightly clearer.

2024-11-04 13:24 UTC, Lucas-C requested changes
Thank you for your contribution @Kaos599 👍

Could you please:
* add a mention of this new command in `README.md`
* add some unit tests in `tests/test_uncompress.py`

You could for example execute this command on all `sample-files/*./*.pdf` files, similar to this: https://github.com/py-pdf/pdfly/pull/15#discussion_r1827712584

2024-11-08 13:24 UTC, Kaos599 commented
SUre

> Thank you for your contribution @Kaos599 👍
> 
> Could you please:
> 
>     * add a mention of this new command in `README.md`
> 
>     * add some unit tests in `tests/test_uncompress.py`
> 
> 
> You could for example execute this command on all `sample-files/*./*.pdf` files, similar to this: [#15 (comment)](https://github.com/py-pdf/pdfly/pull/15#discussion_r1827712584)

Sure i will implement those within few days

2024-11-13 12:54 UTC, Lucas-C commented
Hi @Kaos599

I see that you published a commit on this branch yesterday.
Is is ready for reviewing?
I think that there is still a minor merge conflict to resolve.

2024-11-13 13:51 UTC, Kaos599 commented
@Lucas-C i have been busy with college exams so i just tried a little yesterday. I still need to implement most of the changes, I will get on it soon and will tag you once done.

Thanks for your patience!

2024-11-15 09:22 UTC, closed without merging